name: neat_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - cairo
  - cython
  - graphviz
  - jupyter
  - matplotlib
  - pyglet
  - python-graphviz
  - swig
  - pip
  - pip:
      - gizeh
      - moviepy
      - pygame
      - pyspice
      - git+https://github.com/Finebouche/neat-python.git # -e ../../other/neat-python
      - gymnasium[box2d]
